### ISSUE TITLE
大佬你好，请教下二进制安装的prometheus如何监控k8s的pod

### ISSUE THREAD

**Issue by legolas-zeng** [heyangguang/kubernetes-doc#1]
我网上搜了很多教程，设置prometheus.yml
```
  - job_name: 'kubernetes-pods'
    scheme: https
    kubernetes_sd_configs:
      - api_server: https://192.168.3.17:6443
        role: pod
        bearer_token: "*************"
        tls_config:
          insecure_skip_verify: true
    tls_config:
      insecure_skip_verify: true
    bearer_token: "**************"
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - source_labels: [__address__]
        separator: ;
        regex: '.*:(.*)'
        target_label: __pod_port__
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_namespace,__meta_kubernetes_pod_name, __pod_port__]
        separator: ;
        regex: (.*);(.*);(.*)
        target_label: __metrics_path__
        replacement: /api/v1/namespaces/$1/pods/$2:$3/proxy/metrics
        action: replace
      - source_labels: [__address__]
        separator: ;
        regex: (.*)
        target_label: __address__
        replacement: 192.168.3.17:6443
        action: replace
```
重启prometheus后。在pod的那栏显示context deadline exceeded错误。求大佬指点。
